name: 'CI -> Pipeline'

on:
    pull_request:
        branches: [stable]
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:
    lint:
        name: 'Lint'
        runs-on: ubuntu-22.04
        permissions: write-all
        steps:
          - name: 'Checkout'
            uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
            with:
              persist-credentials: false

          - name: 'Setup Bun'
            uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1.2.1

          - name: 'Setup dependencies'
            run: bun install --frozen-lockfile

          - name: 'Run lint'
            run: bun run lint